name: Run PHPUnit Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - name: Cloner le dépôt
      uses: actions/checkout@v3

    - name: Installer PHP, Composer et les extensions
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2.12'
        extensions: mbstring, intl, pdo, pdo_mysql

    - name: Installer les dépendances
      run: composer install

    - name: Exécuter PHPUnit
      run: vendor/bin/phpunit --configuration phpunit.xml
