name: Run PHPUnit Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  php-tests:
    name: PHPUnit on PHP 8.2
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: tests_db
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          coverage: xdebug

      - name: Install Composer dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Copy CI environment and migrate
        run: |
          cp .env.ci .env
          php spark migrate --quiet

      - name: Run PHPUnit tests with coverage
        run: vendor/bin/phpunit --coverage-text
